### ISSUE TITLE
Buttons/levers/mechdoors megathread 

### ISSUE THREAD

**Issue by Zedb0T** [OpenGOAL-Mods/OG-NoOOJ-II#26]
- [x] Rescue friends
- [x] Power Switches
- [x] Metal Head nest Screw lever
- [x] Drill platform leveler and titansuit doors?
- [x] Ruins Titansuit doors?

**Comment by dallmeyer** [comment]
assigning myself as placeholder for Majora12

**Comment by dallmeyer** [comment]
👍
